-- Generated by Interactive Seeder on 2026-02-08T06:44:55.817Z

-- USERS
INSERT INTO users (id, email, password, firstName, lastName, role, branchId, isActive, createdAt, updatedAt) VALUES
  ('e52e7368-07bd-4e14-a7af-73be96cbcbdd', 'bahati@g24sec.com', '@Cutlerkmx701', 'System', 'Administrator', 'admin', NULL, TRUE, '2026-02-08T06:44:01.317Z', '2026-02-08T06:44:01.317Z');

